### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by stridjj** [Noxturnix/Spammer-Grab#4]
The problem is that I cant use --proxy key. It doesn't work. It's possible that I'm not using it correctly. 
  The following steps were done:
1) android app "termux" was downloaded (the script is launching on android)
2) sudo apt install git
    git clone https://github.com/Noxturnix/Spammer-Grab
cd Spammer-grab
./auto-install.sh

3) python2 spammer.py --proxy 46.45.146.210:8080 --delay 15 (phone)
prixy is Turkey (istanbul)

then 

[ ! ] [  thread-1 ] ConnectionError thrown! Sleeping for 15s . . .
message was received.
I should mention that script was launched WITHOUT wifi, but WITH mobile internet from Russia.
I haven't any idea,why this happened. Any help is 
appreciated .

**Comment by Noxturnix** [comment]
Hello @stridjj,

I've got the email from you, but unfortunately, I can't reply to your email due to an email forwarding issue. So, sorry for the inconvenience.

Let's get back to the issue. I'm not sure if the problem is about the loosen `socks` dependencies of the `requests` module on your device. You can basically execute the command below in your Termux app and check if it solves the issue.

    pip2 install requests[socks]

Please let me know if this works for you and I'll make an upgrade for the `auto-install.sh` script.

Thanks,

**Comment by stridjj** [comment]
$pip2 install requests[socks] was successful (Successfully installed
PySocks-1.6.8 is the termux message) so, now the Spammer-Grab message is

[!][thread-1][429 Too Many Requests] Sleeping for 15s . . .
the command was the same python2 spammer.py --proxy (as I mentioned above)

Also I have tried without --proxy key, but with proxy set up in my phone's
wi-fi settings. (and I took another new proxy) Result is the same:
[!][thread-0][429 Too Many Requests] Sleeping for 15s . . .

thanks.

**Comment by stridjj** [comment]
so, is there any way to make it work properly?

**Comment by Noxturnix** [comment]
Seems the number has received GACs too many times at the same time. Maybe someone else is using this script to send a message to the number. So, you can try it again later or send to another number.

**Comment by stridjj** [comment]
according to my investigation the site https//p.grabtaxi.com is working that way: it doesn't save (store) my (attacker) external IP. It stores the victim's phone number. So that is right that when I receive "Too many requests" it's sufficient  to change the victim's phone number and then the attack continues. But the problem now is that I can't continue to work with my first victim... It's necessary to change victim (but I don't want it). So if I'm correct and it works like was said above (if it isn't please correct me) I have an idea how to solve this. But I think it needs another topic, so I'm opining new issue and closing this one.
  And there is another question: what is the purpose of --proxy in that way when the GAC site doesn't store my (attacker) IP?

**Comment by NoTypen** [comment]
Hi
I got  the same problem with Spammer-Grab:
[!][thread-0][429 Too Many Requests]
I have already read about it. Tried to use proxychains with DNS change, it works, but problem do not gone. After 20 sms it does not work. It was an idea to make some changes in code, but file is compile))
So, can you help me to fix it? or give some advice) I am only apprentice in code so I rely on your help)

**Comment by Noxturnix** [comment]
I preferred `uncompyle6` for decompiling the class file
